### PR TITLE
fix(gs): Handle moves as invalid while a player is dead

### LINKED ISSUE #121: Restrict movements while dead
Only allow a movement that causes the player to jump back, potentially undoing their death

### PR DESCRIPTION
**Pull request by jespertheend**
Fixes #121

### CODE REVIEW

**Review by splixcord — COMMENTED** [review]
Looks good, I have a few edge cases though:

The invalid moves stay at the beginning of the queue, so moves after it will not get processed to have a chance of undoing the death, although I don't know if this can happen in a normal situation
The old server removes invalid and future moves from the queue if dead and loops onto the next ones

An undo not far enough to undo the player's own death would also be marked as invalid, it might cause situations such as players to continue going straight when they tried to turn while a second player kills and undoes their death
Turning without undo but when running into something that kills them on the same tick should also be allowed at that position

**Comment by jespertheend** [comment]
> The invalid moves stay at the beginning of the queue
Should be fixed now 👍 

> continue going straight when they tried to turn while a second player kills and undoes their death
I think this would probably get fixed with #94. Not sure how the old server handled this but it seems like a pretty rare situation anyway.

> Turning without undo but when running into something that kills them on the same tick should also be allowed
I gave this some more thought, I don't think this situation is possible. If you are at a location that would kill you, then turning without changing your position would per definition still mean you are dead. Unless I'm missing something?

**Comment by splixcord** [comment]
> Turning without undo but when running into something that kills them on the same tick

Running into player head, wall or own trail while there's an item in the movement queue.
In the old server when it reaches the block it kills the player and turns in the same tick, but trying to turn after death gets ignored. However on second thought maybe this behaviour shouldn't be perfectly copied.

If it's running into a player head or a player killing your trail then that death can be undone by the other player, should the revived player keep going straight (turn ignored) or have their turn applied? Won't be fixed by 94
Sending an undo while dead that's not far enough to undo your death (because another player is responsible for it, for example hitting your trail somewhere and then undoing after you did the move) your move would still currently get ignored.

**Comment by jespertheend** [comment]
Ah I see, I think the previous approach would fix this then. The version from before I cleared the queue I mean.
In that case the entries would remain in the queue and would be applied when the death is undone.

**Comment by splixcord** [comment]
> Sending an undo while dead that's not far enough to undo your death (because another player is responsible for it, for example hitting your trail somewhere) your move would still currently get ignored.

This wasn't fixed and valid undo moves are ignored now

**Comment by jespertheend** [comment]
Yeah but I think that's fine because they are only ignored if there was an invalid move first. And at that point you have kind of already messed up enough to not deserve an undo I think.
The alternative is that entries are removed from the queue and they are lost when you do end up coming back to life, which is much worse I think.

**Pull request merged**
