### PR TITLE
fix(gs): Players receive invalid skin ids when more than 11 players join with the same skin

### PR DESCRIPTION
**Pull request by abhishek276533**
Fixes: #28 

The fix was to add a clamp method inside `serverToClientColorId`

### CODE REVIEW

**Comment by jespertheend** [comment]
I'm not sure if this is the correct way to fix this.
I think something is going wrong in `skinColorIdForPlayer()` causing it to return `-1`, which shouldn't happen in the first place.

**Comment by abhishek276533** [comment]
Its happening due to `skinColorIdForPlayer()` function which will assign `fakeSkinId` value as `0` for playerId which is multiple of `12` and `serverToClientColorId()` function returns `-1` for that

**Comment by jespertheend** [comment]
Ah sorry, I meant to say `skinColorIdForPlayer()` is not supposed to return `0`. As can be seen in the `Player` constructor, if the `#skinColorId` is `0` then it picks a random color between `1` and `VALID_SKIN_COLOR_RANGE`.
At no point should any player ever have `0` as skin, so `skinColorIdForPlayer()` should never be returning `0` either.

**Comment by abhishek276533** [comment]
Thank you for pointing out the issue with the `skinColorIdForPlayer()` function, now I get it. 
We can add a check inside `skinColorIdForPlayer()` to check if `fakeSkinId` equals `0` and increase the count by `1`.

**Comment by jespertheend** [comment]
I'd like to figure out why `skinColorIdForPlayer()` is returning `0` in the first place. I tried making sure each color occurs just as frequently, but I failed a bit I guess.
I think the trick is to change `SKINS_COUNT - 1` into `SKINS_COUNT - 2`, that way the first value ranges from `0` to `SKINS_COUNT - 3`. And then `return fakeSkinId + 1` to make it range from `1` to `SKINS_COUNT - 2` again.

But I'd have to do some debugging to verify this. Also I think some of the higher skin colors may have been left out from this range.

**Comment by jespertheend** [comment]
This should now have been fixed in #39, so I'll close this if that's ok.

**Pull request closed without merging**
